spring:
  profiles:
    active: local # 기본 환경 선택
server:
  port: 8081
  compression:
    enabled: true
    excluded-user-agents:
    mime-types:
    - text/html
    - text/xml
    - text/plain
    - text/css
    - text/javascript
    - application/javascript
    min-response-size: 2048
file:
  upload-dir : "D:/file/"
---

spring:
  profiles: local
  datasource-m:
    url: jdbc:mariadb://localhost:3306/master
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: root123!
  datasource-s:
    url: jdbc:mariadb://localhost:3307/master
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: root123!
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
        